Revert "qcom: Automatically set TARGET_USES_COLOR_METADATA for msm8996/8"
Causes following error:
hardware/qcom/display-caf/msm8996/libqdutils/qdMetaData.h:34:10: fatal
error: 'color_metadata.h' file not found

This reverts commit 354aad78fa462eb7e4b5650059ad4ec1634abab9.